const productos = [
  {
    id: "IA04-952",
    nombre: "Boton Lingual Ceramico Base Redonda pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Ceramicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/LingualRedondo.png",
    imgExtra: ["","",""],
  },
  {
    id: "IA04-901",
    nombre: "Hook Lingual Ceramico pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Ceramicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/LingualHook.png",
  },
  {
    id: "IA04-151",
    nombre: "Boton Lingual Metalico Base Eliptica pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/BotonEliptica.png",
  },
  {
    id: "IA04-314",
    nombre: "Boton Lingual Metalico con hook Base Redonda pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/BotonHook.png",
  },
  {
    id: "IA04-604",
    nombre: "Ojal Tipo Tubo Metalico Base Curva pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "IA17-201",
    nombre: "Aro Lingual Metalico con Base Redonda pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "IA17-101",
    nombre: "Cadena de Traccion Metalica Base Redonda pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/Cadena1.png",
  },
  {
    id: "IA05-101L",
    nombre: "Hook Crimpable Metalico Largo 3mm pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/HookCrimpable.png",
  },
  {
    id: "IA05-301",
    nombre: "Hook Spiral Metalico Izquierdo 8,7mm pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/MultiHookCrimp.png",
  },
  {
    id: "IA05-302",
    nombre: "Hook Spiral Metalico Derecho 8,7mm pack 10 unidades",
    categoria: "Accesorios",
    subcategoria1: "Intraorales",
    subcategoria2: "Metalicos",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/MultiHookCrimp.png",
  },
  {
    id: "BR812-155",
    nombre: "Lokactive Interactivo ROTH 022 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Autolig interactivo metalico / malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/LockActive1.png",
  },
  {
    id: "TC-R22-02",
    nombre: "Thomas Clear Allumina Autoligado Pasivo ROTH 022 7X7 U/L",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Ceramico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/ThomasC.png",
  },
  {
    id: "TC-M22-02",
    nombre: "Thomas Clear Allumina Autoligado Pasivo MBT 022 7X7 U/L",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Ceramico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/ThomasC.png",
  },
  {
    id: "TM-R22-02",
    nombre: "Thomas Metalico Autoligado Pasivo ROTH 022 7X7 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Metalico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/ThomasM2.png",
  },
  {
    id: "TM-M22-02",
    nombre: "Thomas Metalico Autoligado Pasivo MBT 022 7X7 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Metalico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/ThomasM2.png",
  },
  {
    id: "1010135",
    nombre: "O-Eyes Metalico Autoligado Pasivo  ROTH 7X7 022 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Metalico",
    marca: "OO Medical",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Oeyes1.png",
  },
  {
    id: "1010131",
    nombre: "O-Eyes Metalico Autoligado Pasivo  MBT 7X7 022 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Autoligado Pasivo Metalico",
    marca: "OO Medical",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Oeyes1.png",
  },
  {
    id: "E3-R22-02",
    nombre: "Elegan lll Allumina Ceramic Bracket ROTH 022 5X5 U/L",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Conv. Ceramico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Elegant.png",
  },
  {
    id: "E3-M22-02",
    nombre: "Elegan lll Allumina Ceramic Bracket MBT 022 5X5 U/L",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Conv. Ceramico",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Elegant.png",
  },
  {
    id: "BR612-15",
    nombre: "MIM Trumpet mini ROTH 022 5X5U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/TrumpetMIMMesh.png",
  },
  {
    id: "BR622-15",
    nombre: "MIM Trumpet mini MBT 022 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/TrumpetMIMMesh.png",
  },
  {
    id: "BR712-15",
    nombre: "Trumpet mini ROTH 022 Monoblock 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Monoblock",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/TrumpetMonoBlock.png",
  },
  {
    id: "BR722-15",
    nombre: "Trumpet mini MBT 022 Monoblock 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Monoblock",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/TrumpetMonoBlock.png",
  },
  {
    id: "GA-R22-02",
    nombre: "Galaxy 2.0 Std Bracket ROTH Monoblock 022 5X5 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Monoblock",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Galaxy.png",
  },
  {
    id: "GA-M22-02",
    nombre: "Galaxy 2.0 Std Bracket MBT Monoblock 022 5X5 U/L",
    categoria: "Brackets",
    subcategoria1: "Metalico",
    subcategoria2: "Caso Bracket Conv. Metalico / Monoblock",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Galaxy.png",
  },
  {
    id: "BR212-35",
    nombre: "Zafiro Roth 022 con posicionador 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Conv. Zafiro",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Zafiro1.png",
  },
  {
    id: "BR222-35",
    nombre: "Zafiro MBT 022 con posicionador 5X5UL",
    categoria: "Brackets",
    subcategoria1: "Ceramico",
    subcategoria2: "Caso Bracket Conv. Zafiro",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Brackets/Zafiro1.png",
  },
  {
    id: "LE-H03",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/4 Heavy 6,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/4 H",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-L03",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/4 Light 2,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/4 L",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-M03",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/4 Medium 3,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/4 M",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-H01",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/8 Heavy 6,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/8 H",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-L01",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/8 Light 2,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/8 L",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-M01",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 1/8 Medium 3,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "1/8 M",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-H02",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/16 Heavy 6,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/16 H",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-L02",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/16 Light 2,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/16 L",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-M02",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/16 Medium 3,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/16 M",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-H05",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/8 Heavy 6,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/8 H",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-L05",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/8 Light 2,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/8 L",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-M05",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 3/8 Medium 3,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "3/8 M",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-H04",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 5/16 Heavy 6,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "5/16 H",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-L04",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 5/16 Light 2,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "5/16 L",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "LE-M04",
    nombre: "Elasticos Intraorales Latex pack 5000, 50 unidades 5/16 Medium 3,5 oz",
    categoria: "Elastomeros",
    subcategoria1: "Elasticos Intraorales Latex",
    subcategoria2: "5/16 M",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-C06",
    nombre: "Cadena Elastica Plateada Cerrada Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Cerrada",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-C27",
    nombre: "Cadena Elastica Transparente Cerrada Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Cerrada",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EL-NA",
    nombre: "Ligaduras Elastomericas Colores Surtidos pack 1040 -",
    categoria: "Elastomeros",
    subcategoria1: "Ligadura elastica",
    subcategoria2: "Colores surtidos",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-S06",
    nombre: "Cadena Elastica Plateada Corta Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Corta",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-S27",
    nombre: "Cadena Elastica Transparente Corta Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Corta",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-L06",
    nombre: "Cadena Elastica Plateada Larga Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Larga",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EC-L27",
    nombre: "Cadena Elastica Transparente Larga Rollo 4,6 mts",
    categoria: "Elastomeros",
    subcategoria1: "Cadena Elastica",
    subcategoria2: "Larga",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EL-N40",
    nombre: "Ligaduras Elastomericas Perladas pack 1040 -",
    categoria: "Elastomeros",
    subcategoria1: "Ligadura elastica",
    subcategoria2: "Perlada",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EL-N06",
    nombre: "Ligaduras Elastomericas Plateadas pack 1040 -",
    categoria: "Elastomeros",
    subcategoria1: "Ligadura elastica",
    subcategoria2: "Plateada",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "EL-N27",
    nombre: "Ligaduras Elastomericas Transparentes pack 1040 -",
    categoria: "Elastomeros",
    subcategoria1: "Ligadura elastica",
    subcategoria2: "Transparente",
    marca: "Creative Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "66-6001",
    nombre: "ALIGNER PLIER HOLE PUNCH",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Alineadores",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6001-3.png",
  },
  {
    id: "66-6003",
    nombre: "ALIGNER PLIER HORIZONTAL ALG",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Alineadores",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6003-3.png",
  },
  {
    id: "66-6004",
    nombre: "ALIGNER PLIER VERTICAL ALG",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Alineadores",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6004-3.png",
  },
  {
    id: "66-6005",
    nombre: "ALIGNER PLIER TEAR DROP",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Alineadores",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6005-3.png",
  },
  {
    id: "66-6002",
    nombre: "ALIGNER PLIER PUNCH PLIER",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Alineadores",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6002-3.png",
  },
  {
    id: "66-6501",
    nombre: "STD BRACKET HOLDER",
    categoria: "Instrumentos",
    subcategoria1: "Pinza",
    subcategoria2: "Brackets/Tubos",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6501-1.png",
  },
  {
    id: "66-6505",
    nombre: "DELUX BRACKET HOLDER",
    categoria: "Instrumentos",
    subcategoria1: "Pinza",
    subcategoria2: "Brackets/Tubos",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6505-1.png",
  },
  {
    id: "66-5001",
    nombre: "HARD WIRE CUTTER",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Corte",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5001-1.png",
  },
  {
    id: "66-5005",
    nombre: "PIN & LIGATURE CUTTER MM",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "corte",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5005-1.png",
  },
  {
    id: "66-5006",
    nombre: "PIN & LIGATURE CUTTER MM LONG",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "corte",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5006-1.png",
  },
  {
    id: "66-5015",
    nombre: "DISTAL END CUTTER FLUSH STRIP",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "corte",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5015-1.png",
  },
  {
    id: "66-5013",
    nombre: "DISTAL END CUTTER FLUSH HOLE",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "corte",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5013-1.png",
  },
  {
    id: "66-6405",
    nombre: "MATHIEU ELAST",
    categoria: "Instrumentos",
    subcategoria1: "Pinza",
    subcategoria2: "Mathieu",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6405-1.png",
  },
  {
    id: "66-6403",
    nombre: "MATHIEU LIG MET",
    categoria: "Instrumentos",
    subcategoria1: "Pinza",
    subcategoria2: "Mathieu",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/6403-1.png",
  },
  {
    id: "66-5027",
    nombre: "WEINGART TC",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5027-1.png",
  },
  {
    id: "66-5030",
    nombre: "WEINGART FINE",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5030-1.png",
  },
  {
    id: "66-5041",
    nombre: "HOOK CRIMPING PLIER",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5041-1.png",
  },
  {
    id: "66-5039",
    nombre: "DIRECT B. BRACKET REMOVER STR",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5039-1.png",
  },
  {
    id: "66-5038",
    nombre: "DIRECT B. BRACKET REMOVER AGL",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5038-1.png",
  },
  {
    id: "66-5090",
    nombre: "STEP PLIER 1MM",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5090.1-1.png",
  },
  {
    id: "66-5091",
    nombre: "STEP PLIER .75 MM",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5090.75-1.png",
  },
  {
    id: "66-5097",
    nombre: "TORQUE PLIER SET WITH KEY",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Alicates/5097-1.png",
  },
  {
    id: "665185",
    nombre: "NITI CINCH BACK PLIER",
    categoria: "Instrumentos",
    subcategoria1: "Alicate",
    subcategoria2: "Utilitario",
    marca: "Sikander",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
  },
  {
    id: "BT622-4410",
    nombre: "Tubo CD 1er Molar MBT, COSY lll Base Asimetric UL/LR",
    categoria: "Tubos Molares",
    subcategoria1: "1er Molar MBT",
    subcategoria2: "Tubos Molare 1er molar CD SI/ID Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/Tubo1.png",
  },
  {
    id: "BT612-4410",
    nombre: "Tubo CD 1er Molar ROTH, COSY lll Base Asimetric UL/LR",
    categoria: "Tubos Molares",
    subcategoria1: "1er Molar Roth",
    subcategoria2: "Tubos Molare 1er molar CD SI/ID Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/Tubo1.png",
  },
  {
    id: "BT722-6410",
    nombre: "Tubo CD 2do Molar MBT, COSY lll Base Asimetric UL/LR",
    categoria: "Tubos Molares",
    subcategoria1: "2do Molar MBT",
    subcategoria2: "Tubos Molare 2do molar CD SI/ID Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/Tubo1.png",
  },
  {
    id: "BT712-6411",
    nombre: "Tubo CD 2do Molar ROTH, COSY lll Base Asimetric UL/LR",
    categoria: "Tubos Molares",
    subcategoria1: "2do Molar Roth",
    subcategoria2: "Tubos Molare 2do molar CD SI/ID Malla",
    marca: "3B Ortho",
    precio: 50,
    disponibilidad: true,
    enOferta: false,
    img:"/Accesorios-Todos/Tubo1.png",
  },
];

export default productos;
